# Generated by Django 5.1.6 on 2025-02-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('intermediate', 'Intermediate'), ('senior', 'Senior')], max_length=50),
        ),
    ]
