# Generated by Django 5.1.6 on 2025-02-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_salary_max_alter_job_salary_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
