# Generated by Django 5.1.6 on 2025-02-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_companyprofile_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='education_experience',
            field=models.TextField(blank=True, help_text='Enter educational and experience requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Enter skills in point form'),
        ),
    ]
