# Generated by Django 5.1.6 on 2025-02-19 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_application_deadline_job_education_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')]),
        ),
    ]
