# Generated by Django 5.1.6 on 2025-02-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_companyprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
