# Generated by Django 5.1.6 on 2025-02-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_testimonial_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('tech', 'Technology'), ('engineering', 'Engineering'), ('medicine', 'Medicine'), ('construction', 'Construction'), ('manufacturing', 'Manufacturing')], default='tech', max_length=50),
            preserve_default=False,
        ),
    ]
