# Generated by Django 5.1.6 on 2025-02-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('tech', 'Technology'), ('engineering', 'Engineering'), ('medicine', 'Medicine'), ('construction', 'Construction'), ('manufacturing', 'Manufacturing'), ('law', 'Law')], max_length=50),
        ),
    ]
