# Generated by Django 5.1.6 on 2025-02-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_blogcategory_blogpost_blogreply_bloglike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='blogreply',
            options={'verbose_name_plural': 'Replies'},
        ),
    ]
