# Generated by Django 5.1.6 on 2025-02-27 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_blogcategory_options_alter_blogreply_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogreply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='jobs.blogreply'),
        ),
    ]
